version: '3'
services:
  mysql:
    container_name: mysql-db4
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - '3306:3306'
    volumes:
      - './sql/create.sql:/docker-entrypoint-initdb.d/1.sql'
      - './sql/insert.sql:/docker-entrypoint-initdb.d/2.sql'
      - './sql/default_view.sql:/docker-entrypoint-initdb.d/3.sql'
      - './sql/insert_item.sql:/docker-entrypoint-initdb.d/4.sql'